apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHFkaTNjcW5i
  CLOUDINARY_KEY: Mjg4MzM1MzM5NzI0OTI3
  CLOUDINARY_SECRET: ZUcxNkdfVUNVTWczR2lDZk5Zc09IazZGMXMw
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljMkZvWVdwaGNtRnVhbUZ1YVNJc0ltRWlPaUpqYlcxck5YaHpiV013ZDNkd01uQndlV3Q2ZVhJNGRHczJJbjAuRFFvNkhDbWhfQnJ2MWZfN091WWhSQQ==
  DB_URL: bW9uZ29kYitzcnY6Ly9zYWhhamFyYW5qYW5pOlNhaGFqYUAxMjNAY2x1c3RlcjAuc3hzbXBseS5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
